version: '3'

services:
    frontend-graphql:
        command: bash -c 'yarn && yarn start'
        container_name: frontend-graphql
        expose:
            - '3001'
        image: node:17
        ports:
            - '3001:3001'
        user: node
        volumes:
            - .:/home/node/app
        working_dir: /home/node/app
